[package]
name = "admin-sep"
version = "0.0.1"
edition = "2024"
publish = true
rust-version = "1.87.0"

[lib]
crate-type = ["rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

